version: '3'

volumes:
  files:
    driver: local
services:
  grid:
    container_name: grid
    image: grid:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - files:/grid
